# Generated by Django 3.2 on 2022-02-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=20, verbose_name='Simbolo')),
                ('last_Refreshed', models.DateField(auto_now=True)),
            ],
        ),
    ]
