# Generated by Django 3.2 on 2022-02-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(choices=[(1, '30 Minutos'), (2, '1 Hora'), (3, '1 Dia')])),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=11)),
                ('high', models.DecimalField(decimal_places=4, max_digits=11)),
                ('low', models.DecimalField(decimal_places=4, max_digits=11)),
                ('close', models.DecimalField(decimal_places=4, max_digits=11)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=11)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.ticker')),
            ],
        ),
    ]
