# Generated by Django 3.2 on 2022-01-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='last_Refreshed',
            field=models.DateField(),
        ),
    ]
